自定义异常和运行时异常是不一样的

自定义异常不会自己抛出，需要手动抛出异常，try-catch一下
# 异常分类
>java语言机制上来讲
- Throwable
所有的Exception异常都是继承Throwable，但是Throwable比较基础，最底层，我们通常不会直接使用，在Throwable下面又引伸出来了error和Exception

- error
	- 错误
	- 一个应用程序如果发生了错误，对应的应用程序根本就启动不起来
	- 操作系统的一堆错误，或者是JVM虚拟机上发上的错误 
- Exception 
	- 异常
>一般程序发生了错误，对应就不能继续跑下去了，但是异常不一样，还是可以正常往下运行

Exception是可以通过我们的代码来处理的，比如说空指针异常，运行时的计算异常，我们可以把这些异常try-catch然后把这些错误返回给前端，告知前端这块是没有找到数据的

Error的错误，我们在代码层级是没有办法进行一个操作的所以我们重点关注的异常就是Exception

Exception又分为2个异常，一个是CheckedException 检测异常，一个是RuntimeException运行时异常



### CheckedException
###  RuntimeException

区别：面试

- CheckedException 必须要在代码里面进行处理，如果不处理代码在编译阶段不通过「就是往外throw Exception 如果在没有throw之前对应的编译器是标红的，没有办法编译通过」
- RuntimeException 不一定强制要求在代码里面处理，对应的编译的时候也不会标红


>例子：比如说客户端发送一个请求，去数据库里面查询一个数据，对应的我们有可能查询的到这个数据，有可能查询不到这个数据，
>如果是没有找到这个记录的情况下，应该抛出的的是RuntimeException
>为什么呢？
>因为大家想一下，我们有一个类A然后有一个类B，A需要调用B下面的C方法
>但是有可能对应的B类下没有这个C方法，那么这个时候建议大家抛出的是CheckedException 因为这个时候对应的编译器就是通不过的，编译器就会抛出异常；如果说这个时候你要自己处理，抛出这个异常的话，就是一个CheckedException  
>再比如，你要去磁盘上读取文件，这个时候文件有可能找不到，那如果这个文件找不到的时候也应该抛出一个CheckedException 

>可以把文件的错误路径改成正确的路径，让程序可以读取到文件，这个错误就可以避免。
>所以说这个错误是可以处理的
>所以 CheckedException 是真正意义上的bug


总结：
- 异常可以处理则为 CheckedException
- 对于异常来说是无能为力的则为 RuntimeException
>RuntimeException很多时候是我们开发者没有办法处理的情况
>比说说用户输入id进行搜索，开始用户输入了2，能查询到，后面用户输入了2000，研发是不知道对应的这个结果是否存在 如果这条记录没有被找到，则抛出的是一个 RuntimeException
>这个严格意义上来讲，不是一个代码的bug
>这个场景就是有可能找到，有可能找不到，找不到只是其中的一个场景，但是这不算是一个代码bug

RuntimeException也可被称为UnCheckedException



### 另外角度分类 
- 已知异常
- 未知异常

>比如说代码里面通过if判断然后throw出来的异常就是已知异常，就是主动抛出来的异常。
>对应就是看研发是否主动处理这个异常，研发处理的异常就是已知异常，如果研发对应的思路不是这么严谨，有些异常情况没有考虑到并且没有处理，则就是未知异常
>有很多异常，研发也不知道，对应都直接抛出Exception 这其实就是处理未知异常，这样可以保证未知异常都可以处理









java代码里面直接throw出来的异常不会变成response的统一格式，那么这个response统一格式是我们自己处理的，
大家可以想想，这种异常出现的次数和地方也很多，有可能在service层有可能在model层也有可能在controller层出现异常，

但是我们需要，有一个地方统一去拦截这些异常的地方，然后把所有的异常信息都拦截下来，然后再把Exception处理成我们的response

以上就是我们解决的思路

那么在什么地方去统一拦截这些内容？

如何接受拦截所有的异常

- 创建包名为core的核心包
- 



控制台报错

返回给前端页面
![](https://gitee.com/javaTesteru/picgo/raw/master/images/hogwarts/202204271731584.png)





这个报错返回给前端，不太好，返回给前端，用户就能看到这个报错了，但是我们要用户看到产品很稳定，用了好长时间没有报过错
但是对于系统来说，有可能用了好长时间没有报过错吗？大概率来说，系统总会报错

但是我们让前端用户不能看到这个报错信息，可以给用户一个友好提示，比如说这会人多啦，或者是请稍后再试这种提示

因为我们也不知道用户是谁，如果我们报错信息都暴露出来，是不是对应的黑客或者其他人也可以拿着这个信息去反向攻击我们的系统

所以该封装的时候就把这些报错信息封装上

## 统一异常处理
- 想要异常结果也显示为统一的返回结果对象，并且统一处理系统的异常信息，那么就需要统一异常处理

## 实现
#### 1. 创建统一异常处理器
创建统一异常处理器 专门来处理系统异常


>不去做接口不去实现相关继承，在这里加一个注解
>ControllerAdvice  AOP面向切面编程，对原来对功能没有侵入性，原来什么样子现在还是什么样子  
>我只是在原来的功能的基础上给你扩展出一个功能，统一异常处理功能 @ControllerAdvice



```java
@RestController
@RequestMapping("/user")
@Api(tags = "用户管理模块")
public class UserController {

    @Autowired
    @Qualifier("user")
    private UserService userService;

    @ApiOperation("用户登录接口请求")
    @PostMapping(value = "login", produces = "application/json")
    R loginWithJson(@RequestBody UserDto userDto) {
        int i = 10 / 0;
        return userService.login(userDto);
    }
}

```




>这个类是用@ControllerAdvice注释的，这是一种@Component。它告诉 Spring 拦截（通过 AOP）所有控制器中的所有处理程序方法，并在抛出匹配的异常时执行异常处理程序方法。
>
>在异常处理方法中，您可以记录异常，重定向到用户友好的错误页面，修改响应状态代码，当匹配异常发生时您想要处理的任何自定义逻辑。

```java
@ControllerAdvice
public class GlobalExceptionHandler {
    
    @ExceptionHandler({Exception.class})
    @ResponseBody
    public R exceptionHandler(Exception e) {
        e.printStackTrace();
        return R.error();
    }
    
    
    
}
```

swagger发送请求发现，对应响应是我们自己封装的异常信息，不再是404/500这样的异常信息

- 对应代码该怎么报错就还是怎么报错，但是用户根本看不到不知道



## 特殊异常处理



.ArithmeticException：计算异常
>我能不能只抓这个计算异常的报错。



```
@ExceptionHandler({ArithmeticException.class})  
@ResponseBody  
public R exceptionHandler1(ArithmeticException e){  
    e.printStackTrace();  
    return R.error().message("特殊异常处理");  
}
```

- 但是状态码还是200

![](https://gitee.com/javaTesteru/picgo/raw/master/images/hogwarts/202204281458126.png)



异常分类：
- 全局异常
- 业务异常


### 自定义异常
- ServiceException
```java
package top.testeru.ssmturorials.exception;

/**
 * @program: ssm-turorials
 * @author: testeru.top
 * @description: 运行时异常
 * @Version 1.0
 * @create: 2022/4/27 6:01 PM
 */


/**
 * 业务逻辑异常 Exception
 */
public final class ServiceException extends RuntimeException{
	/**
	 * 业务错误码
	 */
	private Integer code;
	/**
	 * 错误提示
	 */
	private String message;

	public ServiceException(String message) {
		this.message = message;
	}

	public ServiceException(Integer code, String message) {
		this.code = code;
		this.message = message;
	}
	public Integer getCode() {
		return code;
	}
	public ServiceException setCode(Integer code) {
		this.code = code;
		return this;
	}
	public String getMessage() {
		return message;
	}
	public ServiceException setMessage(String message) {
		this.message = message;
		return this;
	}
}

```


- 全局异常类里面引用
```java
@ControllerAdvice
public class GlobalExceptionHandler {


	//    @ResponseStatus(HttpStatus.BAD_GATEWAY)
	@ExceptionHandler({Exception.class})
	@ResponseBody
	public R exceptionHandler(Exception e) {
		e.printStackTrace();
		return R.error();
	}



	@ExceptionHandler({ServiceException.class})
//    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public R servceExceptionHandler(ServiceException se){
		se.printStackTrace();
		return  R.error().code(se.getCode()).message("业务异常 "+ tips);
	}




}
```

结论：
如果运行的时候进入了 ServiceException ，对应的Exception的方法则不进入，只进入一个。
虽然对应的Exception 包含 ServiceException

但是对应Exception也是需要保留，因为我们做的是全局的异常处理，一个系统里面的异常不只是ServiceException


```java


    @ApiOperation("用户登录接口请求")
    @PostMapping(value = "login",produces = "application/json")
    R loginWithJson(@RequestBody UserDto userDto) {
        throw new ServiceException(40001,"999");
    }
    


```

- 运行发现使用自定义服务异常，业务code码按自定义内容显示
- 但是对应http请求状态码还是200
  ![](https://gitee.com/javaTesteru/picgo/raw/master/images/hogwarts/202204281502000.png)


当前表示的是异常，但是状态码肯定不能显示的是200
那如何修改这个http请求的状态码呢？
2种方式：
- 一种在方法上打上对应的注解 ResponseStatus 
  - ResponseStatus 有一个code关键字设置对应的http请求的状态码
  - Exception：
    - 这个是未知异常，而且分析过具体的错误原因不需要也不应该提示给前端，所以对应的http
    - 请求的响应码用500错误码，很模糊的错误，不告诉前端具体的原因
- ResponseStatus

#### 
- 使用注解修改HttpStatus

![](https://gitee.com/javaTesteru/picgo/raw/master/images/hogwarts/202204281506812.png)




```java
package top.testeru.ssmturorials.core;

import org.springframework.core.convert.ConversionFailedException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import top.testeru.ssmturorials.exception.ServiceException;
import top.testeru.ssmturorials.util.R;


//ControllerAdvice  AOP面向切面编程，对原来对功能没有侵入性，原来什么样子现在还是什么样子
//我只是在原来的功能的基础上给你扩展出一个功能，统一异常处理功能
//@ControllerAdvice
@RestControllerAdvice
public class GlobalExceptionHandler {

    String tips = "系统繁忙，请稍后重试";

    @ResponseStatus(HttpStatus.BAD_GATEWAY)
    @ExceptionHandler({Exception.class})
//    @ResponseBody
    public R exceptionHandler(Exception e){
        //记录日志
        //通知运维
        //通知开发
        //控制台打印异常，万一出现异常调试
        e.printStackTrace();
        return R.error().message("非业务异常 "+ tips);

    }


    @ExceptionHandler({ServiceException.class})
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    public R servceExceptionHandler(ServiceException se){
        se.printStackTrace();
        return  R.error().code(se.getCode()).message("业务异常 "+ tips);
    }

    
}

```




{

"code": 400323,

"message": "业务异常 系统繁忙，请稍后重试 RestAPI:POST /user/login",

"data": {}

}
```java
package top.testeru.ssmturorials.exception;

/**
 * @program: ssm-turorials
 * @author: testeru.top
 * @description: 运行时异常
 * @Version 1.0
 * @create: 2022/4/27 6:01 PM
 */


/**
 * 业务逻辑异常 Exception
 */
public final class ServiceException extends RuntimeException{
    /**
     * 业务错误码
     */
    private Integer code;
    /**
     * 错误提示
     */
    private String message;

    public ServiceException(String message) {
        this.message = message;
    }

    public ServiceException(Integer code, String message) {
        this.code = code;
        this.message = message;
    }




    public Integer getCode() {
        return code;
    }


    public ServiceException setCode(Integer code) {
        this.code = code;
        return this;
    }

    public String getMessage() {
        return message;
    }

    public ServiceException setMessage(String message) {
        this.message = message;
        return this;
    }

}

```



